// ==========================================
// quiz.js
// ==========================================
// Runs the quiz gameplay entirely in the browser. The quiz (all
// questions + explanations) was already generated by the AI, so no
// further AI calls happen while playing — this keeps things fast
// and keeps API costs low.

const quizLoading = document.getElementById("quiz-loading");
const quizError = document.getElementById("quiz-error");
const quizGame = document.getElementById("quiz-game");

const quizTitleEl = document.getElementById("quiz-title");
const quizScoreEl = document.getElementById("quiz-score");
const quizStreakEl = document.getElementById("quiz-streak");
const questionCounterEl = document.getElementById("question-counter");
const progressBarEl = document.getElementById("quiz-progress-bar");
const questionTextEl = document.getElementById("question-text");
const choicesListEl = document.getElementById("choices-list");

const feedbackPanel = document.getElementById("feedback-panel");
const feedbackResult = document.getElementById("feedback-result");
const feedbackPoints = document.getElementById("feedback-points");
const feedbackExplanation = document.getElementById("feedback-explanation");
const nextBtn = document.getElementById("next-btn");

const LETTERS = ["A", "B", "C", "D"];
const POINTS_PER_CORRECT = 10;
const STREAK_BONUS_THRESHOLD = 3;
const STREAK_BONUS_POINTS = 5;

let quiz = null;
let quizId = null;
let currentIndex = 0;
let score = 0;
let streak = 0;
let bestStreak = 0;
let correctCount = 0;
let wrongCount = 0;
let answered = false;
let previousReview = null;

function getQuizIdFromUrl() {
  const params = new URLSearchParams(window.location.search);
  return params.get("id");
}

async function loadQuiz() {
  quizId = getQuizIdFromUrl();
  if (!quizId) {
    showError("No quiz was specified.");
    return;
  }

  try {
    const res = await apiFetch(`/api/quiz/${encodeURIComponent(quizId)}`);
    const data = await res.json();

    if (!res.ok) {
      throw new Error(data.error || "Could not load this quiz.");
    }

    quiz = data;
    quizTitleEl.textContent = quiz.title;
    quizLoading.hidden = true;
    quizGame.hidden = false;

    // So Libris can reference "last time you scored..." while the
    // student reviews, and so the result page can show a comparison
    // without needing a second fetch.
    const history = await fetchQuizHistory({ excludeQuizId: quizId, limit: 1 });
    previousReview = history[0] || null;

    renderQuestion();
  } catch (err) {
    showError(err.message || "Could not load this quiz.");
  }
}

function renderQuestion() {
  answered = false;
  feedbackPanel.hidden = true;

  const total = quiz.questions.length;
  const question = quiz.questions[currentIndex];

  questionCounterEl.textContent = `Question ${currentIndex + 1} / ${total}`;
  progressBarEl.style.width = `${((currentIndex + 1) / total) * 100}%`;

  questionTextEl.textContent = question.question;

  choicesListEl.innerHTML = "";

  if (question.type === "identification") {
    renderIdentificationQuestion(question);
  } else {
    renderMultipleChoiceQuestion(question);
  }

  updateStatsDisplay();
}

function renderMultipleChoiceQuestion(question) {
  question.choices.forEach((choice, index) => {
    const btn = document.createElement("button");
    btn.className = "choice-btn";
    btn.innerHTML = `<span class="choice-letter">${LETTERS[index]}</span><span>${choice}</span>`;
    btn.addEventListener("click", () => handleMultipleChoiceAnswer(index, btn));
    choicesListEl.appendChild(btn);
  });
}

function renderIdentificationQuestion(question) {
  const wrapper = document.createElement("div");
  wrapper.className = "identification-wrapper";

  const input = document.createElement("input");
  input.type = "text";
  input.className = "identification-input";
  input.id = "identification-input";
  input.placeholder = "Type your answer...";
  input.maxLength = 200;
  input.autocomplete = "off";

  const submitBtn = document.createElement("button");
  submitBtn.className = "btn btn-primary identification-submit-btn";
  submitBtn.textContent = "Submit Answer";

  const submit = () => handleIdentificationAnswer(input, submitBtn);
  submitBtn.addEventListener("click", submit);
  input.addEventListener("keydown", (e) => {
    if (e.key === "Enter") {
      e.preventDefault();
      submit();
    }
  });

  wrapper.appendChild(input);
  wrapper.appendChild(submitBtn);
  choicesListEl.appendChild(wrapper);

  input.focus();
}

// Normalizes a typed answer so minor differences (casing, spacing,
// punctuation) don't count against the student.
function normalizeAnswer(str) {
  return str
    .trim()
    .toLowerCase()
    .replace(/[.,!?;:'"()\-]/g, "")
    .replace(/\s+/g, " ");
}

function handleMultipleChoiceAnswer(selectedIndex, selectedBtn) {
  if (answered) return;
  answered = true;

  const question = quiz.questions[currentIndex];
  const isCorrect = selectedIndex === question.correctAnswer;

  // Disable all choice buttons and highlight correct/incorrect
  const allButtons = choicesListEl.querySelectorAll(".choice-btn");
  allButtons.forEach((btn, index) => {
    btn.disabled = true;
    if (index === question.correctAnswer) {
      btn.classList.add("correct");
    } else if (index === selectedIndex) {
      btn.classList.add("incorrect");
    }
  });

  const correctAnswerText = question.choices[question.correctAnswer];
  applyAnswerResult(isCorrect, correctAnswerText);
}

function handleIdentificationAnswer(input, submitBtn) {
  if (answered) return;

  const typed = input.value.trim();
  if (!typed) {
    input.focus();
    return;
  }

  answered = true;

  const question = quiz.questions[currentIndex];
  const acceptable = [question.answer, ...(question.acceptableAnswers || [])].map(
    normalizeAnswer
  );
  const isCorrect = acceptable.includes(normalizeAnswer(typed));

  input.disabled = true;
  submitBtn.disabled = true;
  input.classList.add(isCorrect ? "correct" : "incorrect");

  applyAnswerResult(isCorrect, question.answer);
}

// Shared scoring + feedback panel logic for both question types.
function applyAnswerResult(isCorrect, correctAnswerText) {
  const question = quiz.questions[currentIndex];
  let pointsEarned = 0;

  if (isCorrect) {
    correctCount++;
    streak++;
    bestStreak = Math.max(bestStreak, streak);
    pointsEarned = POINTS_PER_CORRECT;

    if (streak >= STREAK_BONUS_THRESHOLD) {
      pointsEarned += STREAK_BONUS_POINTS;
    }

    score += pointsEarned;

    feedbackResult.textContent = "✓ Correct!";
    feedbackResult.className = "feedback-result correct";
    feedbackPoints.textContent = `+${pointsEarned} points`;
  } else {
    wrongCount++;
    streak = 0;

    feedbackResult.textContent = "✗ Incorrect";
    feedbackResult.className = "feedback-result incorrect";
    feedbackPoints.textContent = `Correct answer: ${correctAnswerText}`;
  }

  feedbackExplanation.textContent = question.explanation;
  feedbackPanel.hidden = false;
  updateStatsDisplay();
}

function updateStatsDisplay() {
  quizScoreEl.textContent = `Score: ${score}`;
  quizStreakEl.textContent = `🔥 Streak: ${streak}`;

  // Let Libris answer "what's my score" / "how am I doing" accurately,
  // and reference the student's previous review if there is one.
  window.StudyQuizContext = {
    page: "quiz",
    quizTitle: quiz ? quiz.title : null,
    currentQuestionNumber: currentIndex + 1,
    totalQuestions: quiz ? quiz.questions.length : null,
    score,
    streak,
    bestStreak,
    correctCount,
    wrongCount,
    ...previousReviewContext(previousReview),
  };
}

nextBtn.addEventListener("click", async () => {
  currentIndex++;
  if (currentIndex >= quiz.questions.length) {
    await finishQuiz();
  } else {
    renderQuestion();
  }
});

async function finishQuiz() {
  const total = quiz.questions.length;
  const maxScore = total * POINTS_PER_CORRECT;

  try {
    await apiFetch(`/api/quiz/${encodeURIComponent(quizId)}/result`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ score, correct: correctCount, wrong: wrongCount }),
    });
  } catch (err) {
    // Non-fatal: still let the student see their result even if saving failed.
    console.error("Could not save quiz result:", err);
  }

  const resultData = {
    quizId,
    score,
    maxScore,
    correct: correctCount,
    wrong: wrongCount,
    total,
    bestStreak,
    previousReview,
  };
  sessionStorage.setItem("studyquiz_result", JSON.stringify(resultData));
  window.location.href = "result.html";
}

function showError(msg) {
  quizLoading.hidden = true;
  quizError.textContent = msg;
  quizError.hidden = false;
}

document.addEventListener("DOMContentLoaded", loadQuiz);
